# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kc8vJKxOXSc5LdQlVFgE_7CdUFNilX3s
"""

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from google.auth.transport.requests import Request
from google_auth_oauthlib.flow import InstalledAppFlow
import base64
import os
import re
from transformers import pipeline
from datetime import datetime
from email.utils import parsedate_to_datetime

# Gmail API setup
SCOPES = ['https://www.googleapis.com/auth/gmail.readonly']
creds = None

# Load Gmail API credentials
if os.path.exists('token.json'):
    creds = Credentials.from_authorized_user_file('token.json', SCOPES)

if not creds or not creds.valid:
    if creds and creds.expired and creds.refresh_token:
        creds.refresh(Request())
    else:
        flow = InstalledAppFlow.from_client_secrets_file(
            'client_secret_172294059513-hoj8g1ougfn5lo651q5bnnp4dkbf2lq4.apps.googleusercontent.com.json', SCOPES)
        creds = flow.run_console()
    with open('token.json', 'w') as token:
        token.write(creds.to_json())

service = build('gmail', 'v1', credentials=creds)

# Hugging Face pipelines
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

def clean_email_body(body):
    """Clean email body by removing unnecessary HTML tags and spaces."""
    body = re.sub(r'<[^>]+>', '', body)  # Remove HTML tags
    body = body.replace('\n', ' ').strip()  # Normalize newlines and strip spaces
    return body

def fetch_emails_for_today():
    """Fetch emails received today from the user's Gmail account."""
    results = service.users().messages().list(userId='me', maxResults=100).execute()
    messages = results.get('messages', [])
    emails = []
    today = datetime.utcnow().date()

    for msg in messages:
        try:
            msg_data = service.users().messages().get(userId='me', id=msg['id']).execute()
            payload = msg_data['payload']
            headers = payload.get('headers', [])
            subject = ''
            sender = ''
            date = ''
            for header in headers:
                if header['name'] == 'Subject':
                    subject = header['value']
                if header['name'] == 'From':
                    sender = header['value']
                if header['name'] == 'Date':
                    date = header['value']

            # Parse the date header
            email_date = parsedate_to_datetime(date).date()

            # Filter emails received today
            if email_date == today:
                body = ''
                parts = payload.get('parts', [])
                if parts:
                    for part in parts:
                        if part.get('mimeType') == 'text/plain':
                            data = part['body']['data']
                            body = base64.urlsafe_b64decode(data).decode('utf-8')
                            break  # Prefer plain text
                        elif part.get('mimeType') == 'text/html':
                            data = part['body']['data']
                            body = base64.urlsafe_b64decode(data).decode('utf-8')
                elif 'body' in payload and 'data' in payload['body']:
                    body = base64.urlsafe_b64decode(payload['body']['data']).decode('utf-8')

                body = clean_email_body(body)
                if body.strip():
                    emails.append({'subject': subject, 'sender': sender, 'body': body})
        except Exception as e:
            print(f"Error processing email: {e}")
    return emails

def summarize_email(email_body):
    """Summarize the email using Hugging Face."""
    try:
        if len(email_body) < 50:
            return "Email content too short to summarize."
        summary = summarizer(email_body, max_length=100, min_length=30, do_sample=False)
        return summary[0]['summary_text']
    except Exception as e:
        print(f"Error summarizing email: {e}")
        return "No summary available."

if __name__ == "__main__":
    fetched_emails = fetch_emails_for_today()
    processed_emails = []

    for email in fetched_emails:
        summary = summarize_email(email['body'])
        processed_emails.append({
            'subject': email['subject'],
            'sender': email['sender'],
            'summary': summary
        })

    # Print the results
    print("\nProcessed Emails for Today:\n")
    for email in processed_emails:
        print(f"Subject: {email['subject']}")
        print(f"From: {email['sender']}")
        print(f"Summary:\n{email['summary']}")
        print("-" * 50)